{"time":"2025-04-07T14:58:57.087634+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.9","symlink path":"c:\\Users\\USER\\Desktop\\Projet-IA\\Projet-IA\\wandb\\run-20250407_145855-mbzya17j\\logs\\debug-core.log"}
{"time":"2025-04-07T14:59:01.3296756+01:00","level":"INFO","msg":"created new stream","id":"mbzya17j"}
{"time":"2025-04-07T14:59:01.3296756+01:00","level":"INFO","msg":"stream: started","id":"mbzya17j"}
{"time":"2025-04-07T14:59:01.3316678+01:00","level":"INFO","msg":"handler: started","stream_id":"mbzya17j"}
{"time":"2025-04-07T14:59:01.3316678+01:00","level":"INFO","msg":"sender: started","stream_id":"mbzya17j"}
{"time":"2025-04-07T14:59:01.3337959+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"mbzya17j"}
{"time":"2025-04-07T14:59:01.5705555+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-04-07T15:00:01.200386+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-04-07T15:00:01.2999375+01:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-04-07T15:00:02.0973369+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-04-07T15:00:02.1691525+01:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-04-07T15:00:05.3331762+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-04-07T15:00:05.7731893+01:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-04-07T15:00:37.8020303+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.22.3.29:51023->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T15:00:38.5917465+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/lethyciachaho-ecolec-entrale/UR3-Cobot-Protective-Stops/mbzya17j/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T15:10:54.4060688+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/lethyciachaho-ecolec-entrale/UR3-Cobot-Protective-Stops/mbzya17j/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-04-07T15:23:43.3881443+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/lethyciachaho-ecolec-entrale/UR3-Cobot-Protective-Stops/mbzya17j/file_stream\": read tcp 172.22.3.29:49839->35.186.228.49:443: wsarecv: An existing connection was forcibly closed by the remote host."}
{"time":"2025-04-07T16:09:53.2921358+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-04-07T17:42:41.2037735+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/lethyciachaho-ecolec-entrale/UR3-Cobot-Protective-Stops/mbzya17j/file_stream\": dial tcp 35.186.228.49:443: connectex: An established connection was aborted by the software in your host machine."}
{"time":"2025-04-07T19:51:06.4926189+01:00","level":"INFO","msg":"api: retrying HTTP error","status":502,"url":"https://api.wandb.ai/files/lethyciachaho-ecolec-entrale/UR3-Cobot-Protective-Stops/mbzya17j/file_stream","body":"\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>502 Server Error</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Server Error</h1>\n<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n<h2></h2>\n</body></html>\n"}
